cmaUrl: http://127.0.0.1

gradleParams:
  gradleVersion: 1.3.0
  target: android-21
  buildToolsVersion: 21.1.2
  minSdk: 14
  targetSdk: 21

paths:
  androidSdkHome: /home/srg/Android/Sdk
  keytoolPath: /usr/bin/keytool
  buildsHome: src/main/resources/builds
  templatesHome: src/main/resources/templates
  projectTemplatesHome: src/main/resources/projectTemplates
  downloadsHome: src/main/resources/downloads

swagger:
  resourcePackage: "com.mo_apps.abs.api"
  title: "Android Build System API"
  version: "0.1-SNAPSHOT"

server:
  applicationConnectors:
    - type: http
      port: 40000
  adminConnectors:
    - type: http
      port: 40001
  registerDefaultExceptionMappers: false

httpClient:
  timeout: 3000ms
  connectionTimeout: 3000ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: WARN
  # Logger-specific levels.
  loggers:
    # Sets the level for 'com.example.app' to DEBUG.
    com.mo_apps.abs: DEBUG
  appenders:
    - type: console
